<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>

		<TargetFramework>net9.0-windows7.0</TargetFramework>

		<UseWPF>true</UseWPF>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<RootNamespace>SentinelX</RootNamespace>
		<AssemblyName>SentinelX</AssemblyName>

		<PlatformTarget>x64</PlatformTarget>
		<Prefer32Bit>false</Prefer32Bit>
		<Version>0.83.0</Version>
		<Description>Lokalny asystent i diagnostyka Windows</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Speech" Version="9.0.0" />

		<PackageReference Include="NAudio"
						  Version="3.1.0" />

		<PackageReference Include="Whisper.net"
						  Version="1.9.1" />

		<PackageReference Include="Whisper.net.Runtime"
						  Version="1.9.1" />

		<PackageReference Include="org.k2fsa.sherpa.onnx"
						  Version="1.13.5" />

		<PackageReference Include="SharpCompress"
						  Version="0.50.4" />

		<PackageReference Include="System.Diagnostics.PerformanceCounter"
						  Version="9.0.0" />

	</ItemGroup>

</Project>

