using System.Text.Json;

namespace SentinelX.Services.Creative;

/// <summary>Builds a procedural, low-poly Blender scene and an FBX interchange asset for Roblox import.</summary>
internal static class RobloxBlenderSceneScript
{
    public static string Build(RobloxGameProjectSpec spec)
    {
        (int r, int g, int b) color = spec.Theme switch
        {
            "space" => (92, 125, 255), "underwater" => (53, 202, 220), "fantasy" => (179, 112, 255),
            "cyberpunk" => (39, 244, 198), "cozy" => (255, 184, 114), "nature" => (117, 212, 112),
            "city" => (255, 177, 88), "horror" => (235, 63, 94), "winter" => (138, 211, 255),
            _ => (62, 211, 174)
        };
        string name = JsonSerializer.Serialize(spec.DisplayName);
        string genre = JsonSerializer.Serialize(spec.Genre);
        string theme = JsonSerializer.Serialize(spec.Theme);
        return $$"""
            # Generated by Sentinel X. Run with Blender 3.6+ in a separate process.
            # The script only adds its own collection and saves an OUTPUT COPY; it never clears the current scene.
            # FBX includes selected generated meshes only. Import it into a private Roblox test place first.
            import bpy
            import math
            import os
            from mathutils import Vector

            PROJECT_NAME = {{name}}
            GAMEPLAY_PROFILE = {{genre}}
            THEME = {{theme}}
            OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")
            os.makedirs(OUTPUT_DIR, exist_ok=True)
            SAFE_STEM = "{{spec.Slug}}"
            BLEND_PATH = os.path.join(OUTPUT_DIR, "game_blockout.blend")
            FBX_PATH = os.path.join(OUTPUT_DIR, "game_blockout.fbx")
            COLLECTION_NAME = "Sentinel " + SAFE_STEM + " " + THEME + " Generated"
            ACCENT_RGB = ({{color.r}} / 255.0, {{color.g}} / 255.0, {{color.b}} / 255.0)

            # Blender suffixes duplicate collection names instead of replacing existing user data.
            collection = bpy.data.collections.new(COLLECTION_NAME)
            bpy.context.scene.collection.children.link(collection)

            def make_material(name, color, metallic=0.0, roughness=0.42):
                material = bpy.data.materials.new(name=name)
                material.diffuse_color = (*color, 1.0)
                material.use_nodes = True
                shader = material.node_tree.nodes.get("Principled BSDF")
                if shader:
                    shader.inputs["Base Color"].default_value = (*color, 1.0)
                    shader.inputs["Metallic"].default_value = metallic
                    shader.inputs["Roughness"].default_value = roughness
                return material

            accent = make_material("SX Accent", ACCENT_RGB, 0.25, 0.27)
            accent_soft = make_material("SX Accent Soft", tuple(min(1.0, value * 0.68 + 0.18) for value in ACCENT_RGB), 0.05, 0.38)
            dark = make_material("SX Deep Base", (0.035, 0.055, 0.095), 0.12, 0.58)
            surface = make_material("SX Slate", (0.105, 0.145, 0.205), 0.08, 0.62)
            light = make_material("SX Porcelain", (0.82, 0.89, 1.0), 0.0, 0.3)
            gold = make_material("SX Reward Gold", (1.0, 0.63, 0.18), 0.22, 0.3)

            def adopt_generated(obj, name, material=None):
                for owner in list(obj.users_collection):
                    owner.objects.unlink(obj)
                collection.objects.link(obj)
                obj.name = name
                if material:
                    obj.data.materials.append(material)
                return obj

            def box(name, location, size, material, bevel=0.12, rotation=(0.0, 0.0, 0.0)):
                bpy.ops.mesh.primitive_cube_add(size=1.0, location=location, rotation=rotation)
                obj = adopt_generated(bpy.context.object, name, material)
                obj.dimensions = size
                bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
                if bevel > 0:
                    modifier = obj.modifiers.new("Soft silhouette", "BEVEL")
                    modifier.width = min(bevel, min(size) * 0.22)
                    modifier.segments = 2
                    obj.modifiers.new("Weighted normals", "WEIGHTED_NORMAL")
                return obj

            def crystal(name, location, radius, material):
                bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=1, radius=radius, location=location)
                obj = adopt_generated(bpy.context.object, name, material)
                obj.scale = (0.72, 0.72, 1.55)
                obj.rotation_euler[2] = math.radians(22)
                bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
                return obj

            def cylinder(name, location, radius, depth, material, vertices=12):
                bpy.ops.mesh.primitive_cylinder_add(vertices=vertices, radius=radius, depth=depth, location=location)
                return adopt_generated(bpy.context.object, name, material)

            def torus(name, location, major_radius, minor_radius, material, rotation=(0.0, 0.0, 0.0)):
                bpy.ops.mesh.primitive_torus_add(major_radius=major_radius, minor_radius=minor_radius,
                    major_segments=32, minor_segments=8, location=location, rotation=rotation)
                return adopt_generated(bpy.context.object, name, material)

            # A compact low-poly graybox: a small part budget, legible silhouettes, no downloaded meshes or textures.
            box("Floating foundation", (0, 0, -0.8), (76, 58, 1.6), dark, 0.7)
            box("Central play surface", (0, 0, 0.08), (66, 48, 0.55), surface, 0.4)
            box("North light rail", (0, 24, 0.55), (66, 0.38, 0.4), accent, 0.08)
            box("South light rail", (0, -24, 0.55), (66, 0.38, 0.4), accent_soft, 0.08)
            box("East light rail", (33, 0, 0.55), (0.38, 48, 0.4), accent_soft, 0.08)
            box("West light rail", (-33, 0, 0.55), (0.38, 48, 0.4), accent, 0.08)

            if GAMEPLAY_PROFILE == "obby":
                box("Spawn deck", (-27, 0, 1.0), (12, 12, 1.0), accent, 0.25)
                for index in range(10):
                    x = -19 + index * 4.1
                    y = 5.8 if index % 2 == 0 else -5.8
                    z = 1.4 + (index % 3) * 0.45
                    box("Parkour step %02d" % (index + 1), (x, y, z), (3.5, 3.5, 0.75), accent if index % 2 == 0 else light, 0.28)
                    if index in (2, 5, 8):
                        torus("Checkpoint halo %02d" % index, (x, y, z + 2.0), 1.2, 0.12, gold)
                box("Finish deck", (25, 0, 2.0), (10, 12, 1.0), gold, 0.28)
                for x in (-30, 30):
                    cylinder("Obby beacon", (x, 0, 4.5), 0.45, 8.0, accent, 8)
            elif GAMEPLAY_PROFILE == "racing":
                box("Time trial lane", (0, 0, 0.62), (62, 14, 0.35), dark, 0.18)
                for index in range(7):
                    x = -23 + index * 7.3
                    y = -3.8 if index % 2 == 0 else 3.8
                    box("Race gate %02d left" % index, (x, y - 4.3, 3.4), (0.42, 6.4, 0.42), accent, 0.08)
                    box("Race gate %02d right" % index, (x, y + 4.3, 3.4), (0.42, 6.4, 0.42), accent_soft, 0.08)
                    box("Race gate %02d crown" % index, (x, y, 6.45), (0.42, 8.7, 0.42), gold if index == 6 else light, 0.08)
                    for dash in range(4):
                        box("Lane marker %02d %02d" % (index, dash), (x + 3.5, y, 0.84), (0.9, 0.22, 0.04), light, 0.02)
            elif GAMEPLAY_PROFILE == "tycoon":
                box("Tycoon plot", (0, 0, 1.0), (40, 30, 1.2), surface, 0.32)
                box("Starter factory", (-9, 2, 5.0), (11, 10, 8), accent, 0.55)
                box("Factory glass core", (-9, 2, 9.3), (6, 5, 1.2), light, 0.2)
                cylinder("Collector plinth", (10, -1, 2.4), 5.0, 2.4, gold, 16)
                torus("Collector ring", (10, -1, 3.75), 4.5, 0.16, accent)
                for index in range(5):
                    x = -16 + index * 6.5
                    cylinder("Pipe support %02d" % index, (x, 8, 2.6), 0.42, 3.0, accent_soft, 10)
                for x in (-16, 16):
                    box("Factory tower", (x, 10, 7.0), (2.2, 2.2, 12), dark, 0.28)
            elif GAMEPLAY_PROFILE == "rounds":
                cylinder("Survival arena", (0, 0, 0.9), 17, 1.2, surface, 48)
                torus("Arena perimeter", (0, 0, 1.65), 16.7, 0.32, accent)
                for index in range(8):
                    angle = math.tau * index / 8
                    x, y = math.cos(angle) * 20, math.sin(angle) * 20
                    cylinder("Arena pylon %02d" % index, (x, y, 4.8), 0.65, 8.5, accent_soft if index % 2 else accent, 8)
                    crystal("Round marker %02d" % index, (x, y, 9.6), 0.7, gold if index % 2 else light)
                box("Hazard preview", (0, 0, 2.3), (23, 0.5, 0.5), gold, 0.18)
            else:
                cylinder("Resource dais", (0, 0, 1.15), 10, 1.8, accent_soft, 32)
                torus("Resource halo", (0, 0, 2.2), 8.2, 0.22, gold)
                crystal("Primary resource", (0, 0, 6.6), 3.2, accent)
                for index in range(8):
                    angle = math.tau * index / 8
                    x, y = math.cos(angle) * 14, math.sin(angle) * 14
                    crystal("Floating shard %02d" % index, (x, y, 2.0 + (index % 3) * 0.65), 0.9, accent_soft if index % 2 else light)
                for index, x in enumerate((-20, 20)):
                    box("Interaction station %02d" % index, (x, -4, 2.3), (8, 7, 3.0), gold if index == 0 else accent, 0.32)
                    box("Station sign %02d" % index, (x, -4, 4.1), (6, 0.18, 1.0), light, 0.05)

            # Shared visual landmarks provide orientation without expensive particle systems.
            for index in range(4):
                x = -25 + index * 16.5
                pillar = cylinder("Boundary marker %02d" % index, (x, 20, 2.5), 0.34, 4.5, accent if index % 2 == 0 else accent_soft, 8)
                crystal("Boundary jewel %02d" % index, (x, 20, 5.3), 0.55, gold)

            scene = bpy.context.scene
            scene.render.resolution_x = 960
            scene.render.resolution_y = 540
            scene.render.resolution_percentage = 80
            scene.render.image_settings.file_format = "PNG"
            scene.render.film_transparent = False
            # A factory-startup scene already contains a camera; use a generated wide shot that frames the whole graybox.
            camera_data = bpy.data.cameras.new("Sentinel generated camera")
            camera = bpy.data.objects.new("Sentinel generated camera", camera_data)
            collection.objects.link(camera)
            camera.location = (92, -112, 95)
            target = Vector((0, 0, 2))
            camera.rotation_euler = (target - camera.location).to_track_quat("-Z", "Y").to_euler()
            camera_data.lens = 45
            camera_data.clip_end = 500
            scene.camera = camera
            light_data = bpy.data.lights.new("Sentinel key softbox", "AREA")
            light = bpy.data.objects.new("Sentinel key softbox", light_data)
            collection.objects.link(light)
            light.location = (5, -14, 28)
            light_data.energy = 3200
            light_data.shape = "DISK"
            light_data.size = 16

            # Save a new file and export only our generated mesh objects; no existing collection is removed.
            bpy.ops.wm.save_as_mainfile(filepath=BLEND_PATH)
            mesh_objects = [obj for obj in collection.objects if obj.type == "MESH"]
            if not mesh_objects:
                raise RuntimeError("No generated meshes were created")
            bpy.ops.object.select_all(action="DESELECT")
            for obj in mesh_objects:
                obj.select_set(True)
            bpy.context.view_layer.objects.active = mesh_objects[0]
            bpy.ops.export_scene.fbx(filepath=FBX_PATH, use_selection=True, object_types={"MESH"},
                axis_forward="-Z", axis_up="Y", apply_unit_scale=True, bake_space_transform=False)
            print("SENTINEL_BUILD_OK blend=%s fbx=%s meshes=%d project=%s" % (BLEND_PATH, FBX_PATH, len(mesh_objects), PROJECT_NAME))
            """;
    }
}
